[project]
name = "ron-py"
version = "0.1.0"
description = "Python reader for Rusty Object Notation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "antlr4-python3-runtime>=4.13.2",
]

[dependency-groups]
dev = [
    "antlr4-tools>=0.2.2",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "types-antlr4-python3-runtime>=4.13.0.20251118",
]

[tool.basedpyright]
typeCheckingMode = 'off'
reportImplicitOverride = true
reportIncompatibleMethodOverride = true
ignore = ["visitor.py"]

[tool.mypy]
exclude = ["ron_parser/"]
python_version = 3.14
warn_unused_configs = true
check_untyped_defs = true

[tool.ruff]
line-length = 80
extend-exclude = ['ron_parser/']
